### ISSUE TITLE
No mailboxes backup after update

### ISSUE THREAD

**Issue by SpectreInc** [lucascbeyeler/zmbackup#153] opened 2021-01-15 09:26 UTC
Hello.
- Zmbackup Version: 1.2.5
- Zimbra Version:  8.8.15_ga_3991.FOSS
- Linux Distribution & Version: CentOS Linux release 7.9.2009

After updating from 1.2.3 to 1.2.5 my backup seem to broken and I can't figure out why.
On 1.2.3 I got incremental backups like :

 Here some information about this session:
Size: 6.9M
Accounts: 30
Status: SUCCESS
Regards,
Zmbackup Team
Summary of files:
SESSION: inc-20201205013001 started on Sat Dec  5 01:30:03 CET 2020

with reasonable sizes

On 1.2.5
incremental is about 128Kb to 136Kb so is ldap backup.
every backup ends with success, but is finished within seconds, like : 

here some information about this session:
Size: 136K
Accounts: 31
Status: SUCCESS
Regards,
Zmbackup Team
Summary of files:
SESSION: inc-20210115013002 started on Fri Jan 15 **01:30:03** CET 2021
SESSION: inc-20210115013002 completed in Fri Jan 15 **01:30:06** CET 2021

where it used to be between 1,5 to 2 minutes
only full backups seem to backup everything.

Please help
Matt

Hello again,
where at first my Full backup seemed to be OK there are now broken too.
at 10-1-2021 I got :
Size: 2.5G
Accounts: 32
Status: SUCCESS

Regards,
Zmbackup Team

Summary of files:
SESSION: full-20210110013002 started on Sun Jan 10 01:30:03 CET 2021
full-20210110013002:xxxd@xxx.nl:01/10/21
full-20210110013002:yyy@yyy.nl:01/10/21
full-20210110013002:zzz@zzz.nl:01/10/21
etc.

now I see only :

Here some information about this session:
Size: 140K
Accounts: 32
Status: SUCCESS
Regards,
Zmbackup Team

Summary of files:
SESSION: full-20210124013001 started on Sun Jan 24 01:30:03 CET 2021
SESSION: full-20210124013001 completed in Sun Jan 24 01:30:08 CET 2021
also only a few seconds

**Comment by HcKTR** [comment] 2021-01-16 00:15
Hello, I am having the same situation. Honestly, I thought I was doing wrong. The command I entered: zmbackup -f -m 1test@zimbratest.com
I guess there is a problem with the restore as well.

**Comment by lucascbeyeler** [comment] 2021-02-06 18:57
Hi,

I made some changes to 1.2-version branch. Could you try again, please?

**Comment by lucascbeyeler** [comment] 2021-02-06 19:01
Duplicate of #155

**Closed as completed by lucascbeyeler** 2021-02-06 19:01 UTC
Labels: Bug Report

**Comment by SpectreInc** [comment] 2021-02-07 22:57
Hello Lucas,

I installed  the new version, and as far as I can see it works. Will 
post an update if it runs with incrementals for a week till the next 
Full update.
thanks for the update
