### ISSUE TITLE
No sessions listed after backups have completed

### ISSUE THREAD

**Issue by cthart** [lucascbeyeler/zmbackup#142] opened 2020-02-26 23:11 UTC
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version: Zimbra 8.8.7_GA_1964
- Linux Distribution & Version: Ubuntu 16.04.6 LTS

##### SUMMARY
After backups have completed, there are no sessions listed.

##### STEPS TO REPRODUCE
Installed zmbackup accepting the default options, except I chose sqlite3 format for the session database.
Ran zmbackup -f which took 1hr37mins resulting in 44G of compressed backups.
Ran zmbackup -l with no sessions listed.

Then ran zmbackup -i which took 48mins and resulted in another 23G of compressed backups. In addition, received the "date: invalid date '+%s'" error once for each mailbox while this was running, and also "/bin/bash: line 21: /usr/bin/logger: Argument list too long" twice. See separate issues for these.
Ran zmbackup -l with no sessions listed.

##### ACTUAL RESULTS
```
zimbra@mail[mail2]:~$ zmbackup -l    
+---------------------------+--------------+--------------+----------+----------------------------+
|       Session Name        |    Start     |    Ending    |   Size   |        Description         |
+---------------------------+--------------+--------------+----------+----------------------------+
+---------------------------+--------------+--------------+----------+----------------------------+
```

**Comment by cthart** [comment] 2020-02-27 10:20
I reinstalled zmbackup, this time accepting all the defaults so that the sessions are saved in sessions.txt

I ran a backup using zmbackup -f which completed successfully in 1:38 resulting in 52G of compressed backups.

But sessions.txt is 0 bytes, and unsurprisingly zmbackup -l still returns no sessions.

**Comment by lucascbeyeler** [comment] 2020-12-08 14:49
Closing the issue - can't reproduce on 1.2.5

**Closed as completed by lucascbeyeler** 2020-12-08 14:49 UTC
Labels: Bug Report
