### ISSUE TITLE
Restore issue - nothing restored

### ISSUE THREAD

**Issue by MiguelCSousa** [lucascbeyeler/zmbackup#152] opened 2021-01-12 14:38 UTC
Hello, 

Just tested restore on account:

zmbackup -r -ro full-20210111190754 testmail@xxxx testrestore@xxxx
Restore mail process with session full-20210111190754 started at Tue Jan 12 14:36:41 WET 2021Account testmail@xxxx restored with success
Restore mail process with session full-20210111190754 completed at Tue Jan 12 14:36:41 WET 2021

Nothing seems to happen. And nothing is restored to the account

##### ISSUE TYPE
- Bug Report
- Feature Idea
- Question
- Enhancement

##### ENVIRONMENT VERSION
- Zmbackup Version:
- Zimbra Version:
- Linux Distribution & Version:

##### STEPS TO REPRODUCE
```
```

##### ACTUAL RESULTS
```
```

**Comment by lucascbeyeler** [comment] 2021-02-06 19:01
Duplicate of #155

**Closed as completed by lucascbeyeler** 2021-02-06 19:01 UTC
Labels: Bug Report
