### ISSUE TITLE
Mailbox dump not working

### ISSUE THREAD

**Issue by vadonka** [lucascbeyeler/zmbackup#63] opened 2018-02-12 10:44 UTC
I setup the new 1.2 version.
zmbackup -f backup the ldap (ldiff) but creating an empty tgz mailbox dump. It does not wrote any error log, just not working. Any help about this.?
Every login credentials is valid.

**Comment by lucascbeyeler** [comment] 2018-02-14 15:25
Hello @vadonka,

Could you please answer the following questions? I need all the information about your Zmbackup and the system is running to help you.

##### ENVIRONMENT VERSION
- Zmbackup Version:
- Zimbra Version:
- Linux Distribution & Version:

And could you check your /var/log/messages? Zmbackup send all the logs inside that file now, so if something is not working you will know there...

**Comment by tdemeter** [comment] 2018-02-18 09:37
I have exactly same problem: 
I've installed it on centos 6.9 & zimbra 8.8.6 open sourece.
Also, the httpie package isn't there in centos6's epel repo, so I installed it from "open fuse" repository.
After install I did this command:
zmbackup -f -m user@domain.tld
I got an email, with Successfully message, but the tgz is 0 byte long!
Also I have an error message in the logs:

Feb 18 10:23:22 zimbra tdemeter[18095]: Zmbackup: Mail sended to alerts@domain.tld to notify about the backup routine begin.
Feb 18 10:23:22 zimbra tdemeter[18097]: Zmbackup: Backup session mbox-20180218102322 started on Sun Feb 18 10:23:22 CET 2018
Feb 18 10:23:23 zimbra tdemeter[18121]: Zmbackup: Mailbox - Backup for account info@anotherdomain.tld failed. Error message below:
Feb 18 10:23:23 zimbra tdemeter[18122]: Zmbackup: info@anotherdomain.tld - --2018-02-18 10:23:22--  https://XX.XX.XX.XX:7071/home/info@anotherdomain.tld/?fmt=tgz#012Connecting to XX.XX.XX.XX:7071... connected.#012    WARNING: certificate common name `my.server.tld' doesn't match requested host name `XX.XX.XX.XX'.#012HTTP request sent, awaiting response... 401 must authenticate#012Reusing existing connection to XX.XX.XX.XX:7071.#012HTTP request sent, awaiting response... 404 no such item#0122018-02-18 10:23:23 ERROR 404: no such item.
Feb 18 10:23:23 zimbra tdemeter[18132]: Zmbackup: Backup session mbox-20180218102322 finished on Sun Feb 18 10:23:23 CET 2018
Feb 18 10:23:23 zimbra tdemeter[18147]: Zmbackup: Mail sended to alerts@domain.tld to notify about the backup routine conclusion.
Feb 18 10:23:23 zimbra tdemeter[18149]: Zmbackup: Excluding the temporary files before close.
Feb 18 10:26:53 zimbra tdemeter[20511]: Zmbackup: Excluding the temporary files before close.
Feb 18 10:27:55 zimbra tdemeter[20968]: Zmbackup: Excluding the temporary files before close.


my.server.tld has a valid ssl certification!

Thanks in advance!

**Comment by tdemeter** [comment] 2018-02-18 10:13
Meanwhile i've found /etc/zmbackup and I changed many variables from my IP to my hostname, but I've got same errors:(

**Comment by tdemeter** [comment] 2018-02-19 09:33
Ok. I found that! The installer didn't create th zmbackup user. After I've created it manually  it works like a charm!
I found an other bug with installer. I did an uninstall procedure, and after uninstall I could not install already it because could not add the external centos repo again. (for parallel)

**Comment by lucascbeyeler** [comment] 2018-02-19 18:31
@tdemeter Thanks for your return... sorry for the long delay.

I'm going to fix this before the end of the week. Thanks for your help :+1: 

Regards,
Lucas Costa Beyeler

**Comment by cp38510** [comment] 2018-02-20 08:09
Hello! I test zmbackup, install and "zmbackup -f"  pass correct, but tgz files is 0 byte size.
What should I do to solve this situation?
Zimbra 8.6
zmbackup version: 1.2.0 - Release Candidate 2
/log/var/messages:
https://127.0.0.1:7071/home/1@test1.com/?fmt=tgz#012Connecting to 127.0.0.1:7071... connected.#012WARNING: cannot verify 127.0.
0.1's certificate, issued by '/C=US/ST=N/A/L=N/A/O=Zimbra Collaboration Server/OU=Zimbra Collaboration Server/CN=test1.com':#012  Unable to locally verify the issuer's authority.#012    WARNING: certificate comm
on name 'test1.com' doesn't match requested host name '127.0.0.1'.#012HTTP request sent, awaiting response... 401 must authenticate#012Reusing existing connection to 127.0.0.1:7071.#012HTTP request sent, awaitin
g response... 500 Server Error#0122018-02-20 09:59:04 ERROR 500: Server Error.

**Comment by lucascbeyeler** [comment] 2018-02-22 15:42
@vadonka @cp38510  and @tdemeter Could you guys try again? I made some modifications for the installer to show a message of the why it doesn't create the zmbackup user.

Regards,
Lucas Costa Beyeler

**Comment by cp38510** [comment] 2018-02-26 11:58
@lucascbeyeler I git clone and install again with default settings install.sh on Centos7, during installation I get an error:
ERROR - Can't create the user. Executing rollback process
Error description: ERROR: service.INVALID_REQUEST (invalid request: must be valid email address: zmbackup@)
Removing... Please wait while we made some changes.

the script is run as root
what needs to be done?

**Comment by lucascbeyeler** [comment] 2018-02-26 20:57
@cp38510 Thanks for your return. I'm going to provide an alternative solution for this... The problem is the machine domain is not the same used by the Zimbra. Can you confirm this?

Regards,
Lucas Costa Beyeler.

**Comment by cp38510** [comment] 2018-02-27 12:16
Sorry, but I do not quite understand what "machine domain"

server hostname = test2
domain Zimbra = test1.com

**Comment by lucascbeyeler** [comment] 2018-02-27 19:32
The machine domain I'm saying is the domain part of the hostname... sorry for the bad explanation :(

Without that the script always crash during the installation.

**Comment by lucascbeyeler** [comment] 2018-03-27 00:25
Hello @vadonka @tdemeter and @cp38510 

Sorry for the long delay, but i'm closing this issue because the bug is fixed in the 1.2-version branch. Until the end of this week a new version will be released.

Thanks for your support.

Lucas Costa Beyeler

**Closed as completed by lucascbeyeler** 2018-03-27 00:25 UTC
Labels: Bug Report
