### ISSUE TITLE
I can't restore backup file to mailbox

### ISSUE THREAD

**Issue by ozererik** [lucascbeyeler/zmbackup#44] opened 2017-08-09 14:31 UTC
Hi,

I backup my mailboxes via zmbackup. My zmbackup version is 1.1.6

My backup folder is /mnt/zimbra1/. 

But, when I want restore backup to mailbox I get error. It has ozer.erik@safaksaglikgrubu.com.tgz file in /mnt/zimbra1/full-20170809020001

When I use this command: zmbackup -r -m full-20170809020001 ozer.erik@safaksaglikgrubu.com
Answer: No backup found. Impossible to restore

What am I doing wrong?

**Comment by lucascbeyeler** [comment] 2017-08-09 14:55
Hi @ozererik ,

Thanks for your report. I'm checking this bug right now.

Regards,
Lucas Costa Beyeler

**Comment by lucascbeyeler** [comment] 2017-08-13 14:32
Hi @ozererik ,

I'm testing the zmbackup, but I can't reproduce your problem. Can you tell me the version of your Zimbra and OS? Can you check if this backup appears if you use the commando zmbackup -l?

Regards,
Lucas Costa Beyeler

**Comment by ozererik** [comment] 2017-08-14 08:28
Hi @lucascbeyeler ,

My OS Version is CentOS release 6.9 (Final). Zimbra Version is Release 8.7.11_GA_1854.RHEL6_64_20170531151956 RHEL6_64 FOSS edition.

zmbackup -l result is below.

[zimbra@mail ~]$  zmbackup -l

Session: alias-20170809013001
    Size: 72K
Accounts: 18
    Type: Alias Backup

Session: alias-20170810013002
    Size: 72K
Accounts: 18
    Type: Alias Backup

Session: alias-20170811013002
    Size: 44K
Accounts: 11
    Type: Alias Backup

Session: alias-20170812013001
    Size: 72K
Accounts: 18
    Type: Alias Backup

Session: alias-20170813013001
    Size: 44K
Accounts: 11
    Type: Alias Backup

Session: alias-20170814013001
    Size: 72K
Accounts: 18
    Type: Alias Backup

Session: distlist-20170808024830
    Size: 232K
Accounts: 53
    Type: Distribution List Backup

Session: distlist-20170809010001
    Size: 232K
Accounts: 53
    Type: Distribution List Backup

Session: distlist-20170810010001
    Size: 232K
Accounts: 53
    Type: Distribution List Backup

Session: distlist-20170811010001
    Size: 232K
Accounts: 53
    Type: Distribution List Backup

Session: distlist-20170812010001
    Size: 232K
Accounts: 53
    Type: Distribution List Backup

Session: distlist-20170813010001
    Size: 232K
Accounts: 53
    Type: Distribution List Backup

Session: distlist-20170814010001
    Size: 232K
Accounts: 53
    Type: Distribution List Backup

Session: full-20170809020001
    Size: 247G
Accounts: 718
    Type: Full Backup

Session: full-20170813020001
    Size: 8.0K
Accounts: 1
    Type: Full Backup

**Comment by peroda** [comment] 2017-08-17 07:36
I have the same problem. I can not restore account
CentOS Linux release 7.3.1611 (Core)
Zimbra 8.7.3_GA_1750 (build 20170215042321)
[zimbra@mail full-20170817020001]$ zmbackup -v
zmbackup version: 1.1.6

**Comment by lucascbeyeler** [comment] 2017-08-31 18:12
@peroda and @ozererik , Good afternoon,

Sorry for the long delay for this patch. I finally fixed the bug and the version 1.1.7 has this patch included. Can you both try again and, if the problem persist, answer this issue?

Regards,
Lucas Costa Beyeler

**Comment by peroda** [comment] 2017-09-04 07:08
thanks but the patch does not work.

[zimbra@mail ~]$ zmbackup -v
zmbackup version: 1.1.7

**Comment by lucascbeyeler** [comment] 2017-09-04 12:06
@peroda, good morning

Your problem is that you inverted the parameters. Try this way:

zmbackup -r -m full-20170817020001 cuenta@dominio.es

The account is the last thing you inform.

Regards,
Lucas Costa Beyeler

**Comment by peroda** [comment] 2017-09-04 13:12
@lucascbeyeler,  Good afternoon,
Works correctly. Thank you very much

zmbackup -r -m full-20170904020001 cuenta@dominio.es  [OK]
zmbackup -r -ro full-20170904020001 cuenta_origen@dominio.es cuenta_destino@dominio.es [OK]

**Comment by ozererik** [comment] 2017-09-04 14:21
Hi @lucascbeyeler ,

I updated zmbackup.

[zimbra@mail full-20170903193001]$ zmbackup -v
zmbackup version: 1.1.7

My Backup Folder is /mnt/zimbra

My full backup files:

[zimbra@mail full-20170903193001]$ ls -l
total 147752
-rw-r----- 1 zimbra zimbra      791 Sep  3 19:28 bilgi@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra     1535 Sep  3 19:28 bilgi@doganhukuk.com.tgz
-rw-r----- 1 zimbra zimbra     1751 Sep  3 19:29 burcinsen@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra 61383383 Sep  3 19:29 burcinsen@doganhukuk.com.tgz
-rw-r----- 1 zimbra zimbra      758 Sep  3 19:28 isagoktas@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra 15031375 Sep  3 19:29 isagoktas@doganhukuk.com.tgz
-rw-r----- 1 zimbra zimbra      737 Sep  3 19:29 mehtaperdem@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra     1532 Sep  3 19:29 mehtaperdem@doganhukuk.com.tgz
-rw-r----- 1 zimbra zimbra      738 Sep  3 19:29 mervegun@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra 15022348 Sep  3 19:29 mervegun@doganhukuk.com.tgz
-rw-r----- 1 zimbra zimbra     1077 Sep  3 19:28 omer.yilmaz@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra     1518 Sep  3 19:28 omer.yilmaz@doganhukuk.com.tgz
**-rw-r----- 1 zimbra zimbra     1201 Sep  3 19:29 ozer.erik@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra     7242 Sep  3 19:29 ozer.erik@doganhukuk.com.tgz**
-rw-r----- 1 zimbra zimbra      780 Sep  3 19:29 rabiakoc@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra 13370420 Sep  3 19:29 rabiakoc@doganhukuk.com.tgz
-rw-r----- 1 zimbra zimbra     1098 Sep  3 19:29 semraaslan@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra   123868 Sep  3 19:29 semraaslan@doganhukuk.com.tgz
-rw-r----- 1 zimbra zimbra     1004 Sep  3 19:28 serkanyonezer@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra 16260701 Sep  3 19:29 serkanyonezer@doganhukuk.com.tgz
-rw-r----- 1 zimbra zimbra     1119 Sep  3 19:29 yakupminez@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra 14989690 Sep  3 19:29 yakupminez@doganhukuk.com.tgz
-rw-r----- 1 zimbra zimbra      764 Sep  3 19:28 yaseminsenol@doganhukuk.com.ldiff
-rw-r----- 1 zimbra zimbra 15031082 Sep  3 19:29 yaseminsenol@doganhukuk.com.tgz

But I can't restored. 

I use this command: [zimbra@mail full-20170903193001]$ zmbackup -r -m full-20170903193001 ozer.erik@doganhukuk.com
No backup found. Impossible to restore

I can restore backup this command via zmmailbox:

/opt/zimbra/bin/zmmailbox -z -m ozer.erik@doganhukuk.com postRestURL "//?fmt=tgz&resolve=skip" /mnt/zimbra/full-20170903193001/ozer.erik@doganhukuk.com.tgz

What would you suggest?

**Comment by peroda** [comment] 2017-09-04 14:36
@ozererik,  zmbackup_wizard ??
Do you have "WORKDIR=/mnt/zimbra" in file /etc/zmbackup/zmbackup.conf  ??

**Comment by ozererik** [comment] 2017-09-04 14:49
Yes I have,

[17:46:34@0] [root@mail.doganhukuk.com:/mnt/zimbra]# cat /etc/zmbackup/zmbackup.conf
###############################################################################
#                        ZMBACKUP CONFIGURATION FILE                          #
###############################################################################
# This file is used to manage the behavior of the zmbackup. Please edit with
# cautious this file. All the values are configured by the zmbackup_wizard, but
# you can change them if you need, just avoid remove any parameter from this file.
# To regenerate this file, just execute zmbackup_wizard again.
# WARNING - There is a field called DEFAULT. This is not the default value of the
# field. It's just a reminder if you forgot the original value of the field.
###############################################################################

# BACKUPUSER - Used to store the name of the account used by Zimbra server to start
#              and stop the service.
#              DEFAULT: zimbra

BACKUPUSER=zimbra

# WORKDIR - Used to store the backups and where the sessions.txt will be saved.
#           The directory must have as owner the same value as BACKUPUSER.
#           DEFAULT: /opt/zimbra/backup

WORKDIR=/mnt/zimbra

# ADMINUSER - This is the admin account used by zmbackup to backup and restore
#             the messages. WARNING: Do not use the Global Admin Account in this
#             file.
#             DEFAULT: zmbackup@domain

ADMINUSER=zmbackup@doganhukuk.com

# ADMINPASS - This is the password used by zmbackup account to backup and restore
#             the messages. WARNING: Do not use the Global Admin Account in this
#             file.
#             DEFAULT: ODBiY2NkNTkyYjY1YWRlM2FjZTNjYTBh

ADMINPASS=ODBiY2NkNTkyYjY1YWRlM2FjZTNjYTBh

# LDAPSERVER - This is the address where you stored Zimbra's LDAP server in your
#              environment.
#              DEFAULT: 127.0.0.1

LDAPSERVER=ldap://192.168.132.3:389

# MAILHOST - This is the address where you stored Zimbra's zmmailbox service in
#            your environment.
#            DEFAULT: 127.0.0.1

MAILHOST=192.168.132.3

# LDAPADMIN - This is where you inform the ldap admin account to backup and restore
#             accounts, alias, and distribution lists entries.
#             DEFAULT: uid=zimbra,cn=admins,cn=zimbra

LDAPADMIN=uid=zimbra,cn=admins,cn=zimbra

# LDAPPASS - This is where you inform the ldap admin password to backup and restore
#            accounts, alias, and adistribuition lists entries.
#            DEFAULT: SLtPAnSFT

LDAPPASS=SLtPAnSFT

# LOGFILE - The path where zmbackup will save his logs. Don't confuse with sessions.txt.
#           Sessions.txt is hard coded stored in $WORKDIR.
#           DEFAULT: /opt/zimbra/log/zmbackup.log

LOGFILE=/opt/zimbra/log/zmbackup.log

# EMAIL_NOTIFY - After each zmbackup execution, going everything okay or not, a mail
#                is sended to someone to inform that the process is concluded, and
#                show a report of each account backed up.
#                DEFAULT: alionart@doganhukuk.com

EMAIL_NOTIFY=alionart@doganhukuk.com

# MAX_PARALLEL_PROCESS - Here you define how many process zmbackup will use to complete
#                        its tasks. If you want to keep as single thread, configure
#                        this field with the value 1.
#                        DEFAULT: 3

MAX_PARALLEL_PROCESS=3

# ROTATE_TIME - Here you define how many days zmbackup must keep in their archives.
#               This value affect full, incremental, alias and distribution list backups.
#               DEFAULT: 30

ROTATE_TIME=30

# LOCK_BACKUP - Here you define if zmbackup should lock the backup session for only one
#               for each day for each option.
#               DEFAULT: TRUE

LOCK_BACKUP=TRUE

**Comment by lucascbeyeler** [comment] 2017-09-04 14:51
@ozererik , good morning.

Do you have an LDAP session? If yes, I found the bug I hate myself to forgot that!

Regards,
Lucas Costa Beyeler

**Comment by lucascbeyeler** [comment] 2017-09-04 23:51
@ozererik @peroda , good evening!

I made the fix and now is working. Can you both try again the restore?

Regards,
Lucas Costa Beyeler

**Comment by peroda** [comment] 2017-09-05 06:21
@lucascbeyeler, good morning,
 zmbackup work good, but I have noticed that the sent folder is not copied.
Does all folder are backed in full backup?

zmbackup -r -m full-20170904020001 cuenta@dominio.es
Restore mail process started at - Tue Sep  5 08:02:32 CEST 2017

Restoring Session - full-20170904020001
Session full-20170904020001 restored with SUCCESS

Restoring Session - inc-20170829020001
Session inc-20170829020001 restored with SUCCESS

Restoring Session - inc-20170830020001
Session inc-20170830020001 restored with SUCCESS

Restoring Session - inc-20170831020001
Session inc-20170831020001 restored with SUCCESS

Restore mail process completed at - Tue Sep  5 08:02:34 CEST 2017
[zimbra@mail ~]$

**Comment by lucascbeyeler** [comment] 2017-09-05 12:08
@peroda, good morning,

Yes, zmbackup backed all folders except Trash and Spam, but this is a limitation from Zimbra. I already test the send folder and he was backed up normally.

Regards,
Lucas Costa Beyeler

**Comment by peroda** [comment] 2017-09-05 13:22
ok, work with zmbackup 1.1.8.
Thanks.

**Comment by lucascbeyeler** [comment] 2017-09-06 22:18
@ozererik, Can you validate if with this version the problem persist?

**Comment by ozererik** [comment] 2017-09-07 12:09
Unfortunately. I can't restore backup.

[zimbra@mail zimbra]$ zmbackup -v
zmbackup version: 1.1.8

[zimbra@mail zimbra]$ zmbackup -r -m full-20170903193001 ozer.erik@doganhukuk.com
No backup found. Impossible to restore

If it does'nt work, i will restore the backup manually.

**Comment by peroda** [comment] 2017-09-07 12:49
@ozererik, 
It worked for me:
1. I erase all copies
2. I ran zmbackup again:
    -zmbackup -f -al
    -zmbackup -f -dl
    -zmbackup -f

**Comment by lucascbeyeler** [comment] 2017-09-07 12:59
@ozererik, Try again with version 1.1.9 - I removed the full + inc restore from this release.

EDIT:

Do you have a Gitter account? I created a room there where we can talk about this, if you want. I'm online at this moment.

https://gitter.im/zmbackup/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by ozererik** [comment] 2017-09-07 13:58
Yes, I updated to 1.1.9 and it is worked!

[zimbra@mail ~]$ zmbackup -v
zmbackup version: 1.1.9

[zimbra@mail ~]$ zmbackup -r -m full-20170903193001 ozer.erik@doganhukuk.com
Restore mail process started at - Thu Sep  7 16:55:33 +03 2017

Restoring Session - full-20170903193001
Session full-20170903193001 restored with SUCCESS

Restore mail process completed at - Thu Sep  7 16:55:34 +03 2017

**Comment by lucascbeyeler** [comment] 2017-09-07 14:08
@ozererik Good to know :+1: 

I'm closing this issue because now the bug is fixed! Feel free to reopen if the bug return.

Have a nice day and thanks for your support.

Regards,
Lucas Costa Beyeler

**Closed by lucascbeyeler** 2017-09-07 14:08 UTC
Labels: bug
